//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server/", ConfigurationName="ServiceReference1.Calculadora_service")]
    public interface Calculadora_service {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://server/).
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/potenciaRequest", ReplyAction="http://server/Calculadora_service/potenciaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculadoraClient.ServiceReference1.potenciaResponse potencia(CalculadoraClient.ServiceReference1.potenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/potenciaRequest", ReplyAction="http://server/Calculadora_service/potenciaResponse")]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.potenciaResponse> potenciaAsync(CalculadoraClient.ServiceReference1.potenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://server/).
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/sumaRequest", ReplyAction="http://server/Calculadora_service/sumaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculadoraClient.ServiceReference1.sumaResponse suma(CalculadoraClient.ServiceReference1.sumaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/sumaRequest", ReplyAction="http://server/Calculadora_service/sumaResponse")]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.sumaResponse> sumaAsync(CalculadoraClient.ServiceReference1.sumaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://server/).
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/restaRequest", ReplyAction="http://server/Calculadora_service/restaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculadoraClient.ServiceReference1.restaResponse resta(CalculadoraClient.ServiceReference1.restaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/restaRequest", ReplyAction="http://server/Calculadora_service/restaResponse")]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.restaResponse> restaAsync(CalculadoraClient.ServiceReference1.restaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://server/).
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/multiplicacionRequest", ReplyAction="http://server/Calculadora_service/multiplicacionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculadoraClient.ServiceReference1.multiplicacionResponse multiplicacion(CalculadoraClient.ServiceReference1.multiplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/multiplicacionRequest", ReplyAction="http://server/Calculadora_service/multiplicacionResponse")]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.multiplicacionResponse> multiplicacionAsync(CalculadoraClient.ServiceReference1.multiplicacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://server/).
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/divisionRequest", ReplyAction="http://server/Calculadora_service/divisionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculadoraClient.ServiceReference1.divisionResponse division(CalculadoraClient.ServiceReference1.divisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/divisionRequest", ReplyAction="http://server/Calculadora_service/divisionResponse")]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.divisionResponse> divisionAsync(CalculadoraClient.ServiceReference1.divisionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://server/).
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/raizRequest", ReplyAction="http://server/Calculadora_service/raizResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculadoraClient.ServiceReference1.raizResponse raiz(CalculadoraClient.ServiceReference1.raizRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Calculadora_service/raizRequest", ReplyAction="http://server/Calculadora_service/raizResponse")]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.raizResponse> raizAsync(CalculadoraClient.ServiceReference1.raizRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="potencia", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class potenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double i;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double j;
        
        public potenciaRequest() {
        }
        
        public potenciaRequest(double i, double j) {
            this.i = i;
            this.j = j;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="potenciaResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class potenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public potenciaResponse() {
        }
        
        public potenciaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="suma", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class sumaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public sumaRequest() {
        }
        
        public sumaRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumaResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class sumaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sumaResponse() {
        }
        
        public sumaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resta", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class restaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double c;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double d;
        
        public restaRequest() {
        }
        
        public restaRequest(double c, double d) {
            this.c = c;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restaResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class restaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public restaResponse() {
        }
        
        public restaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicacion", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class multiplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double e;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double f;
        
        public multiplicacionRequest() {
        }
        
        public multiplicacionRequest(double e, double f) {
            this.e = e;
            this.f = f;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicacionResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class multiplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multiplicacionResponse() {
        }
        
        public multiplicacionResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="division", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class divisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double g;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double h;
        
        public divisionRequest() {
        }
        
        public divisionRequest(double g, double h) {
            this.g = g;
            this.h = h;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divisionResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class divisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divisionResponse() {
        }
        
        public divisionResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raiz", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class raizRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double k;
        
        public raizRequest() {
        }
        
        public raizRequest(double k) {
            this.k = k;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raizResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class raizResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public raizResponse() {
        }
        
        public raizResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Calculadora_serviceChannel : CalculadoraClient.ServiceReference1.Calculadora_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Calculadora_serviceClient : System.ServiceModel.ClientBase<CalculadoraClient.ServiceReference1.Calculadora_service>, CalculadoraClient.ServiceReference1.Calculadora_service {
        
        public Calculadora_serviceClient() {
        }
        
        public Calculadora_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Calculadora_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calculadora_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calculadora_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraClient.ServiceReference1.potenciaResponse CalculadoraClient.ServiceReference1.Calculadora_service.potencia(CalculadoraClient.ServiceReference1.potenciaRequest request) {
            return base.Channel.potencia(request);
        }
        
        public double potencia(double i, double j) {
            CalculadoraClient.ServiceReference1.potenciaRequest inValue = new CalculadoraClient.ServiceReference1.potenciaRequest();
            inValue.i = i;
            inValue.j = j;
            CalculadoraClient.ServiceReference1.potenciaResponse retVal = ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).potencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.potenciaResponse> CalculadoraClient.ServiceReference1.Calculadora_service.potenciaAsync(CalculadoraClient.ServiceReference1.potenciaRequest request) {
            return base.Channel.potenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.potenciaResponse> potenciaAsync(double i, double j) {
            CalculadoraClient.ServiceReference1.potenciaRequest inValue = new CalculadoraClient.ServiceReference1.potenciaRequest();
            inValue.i = i;
            inValue.j = j;
            return ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).potenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraClient.ServiceReference1.sumaResponse CalculadoraClient.ServiceReference1.Calculadora_service.suma(CalculadoraClient.ServiceReference1.sumaRequest request) {
            return base.Channel.suma(request);
        }
        
        public double suma(double a, double b) {
            CalculadoraClient.ServiceReference1.sumaRequest inValue = new CalculadoraClient.ServiceReference1.sumaRequest();
            inValue.a = a;
            inValue.b = b;
            CalculadoraClient.ServiceReference1.sumaResponse retVal = ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).suma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.sumaResponse> CalculadoraClient.ServiceReference1.Calculadora_service.sumaAsync(CalculadoraClient.ServiceReference1.sumaRequest request) {
            return base.Channel.sumaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.sumaResponse> sumaAsync(double a, double b) {
            CalculadoraClient.ServiceReference1.sumaRequest inValue = new CalculadoraClient.ServiceReference1.sumaRequest();
            inValue.a = a;
            inValue.b = b;
            return ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).sumaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraClient.ServiceReference1.restaResponse CalculadoraClient.ServiceReference1.Calculadora_service.resta(CalculadoraClient.ServiceReference1.restaRequest request) {
            return base.Channel.resta(request);
        }
        
        public double resta(double c, double d) {
            CalculadoraClient.ServiceReference1.restaRequest inValue = new CalculadoraClient.ServiceReference1.restaRequest();
            inValue.c = c;
            inValue.d = d;
            CalculadoraClient.ServiceReference1.restaResponse retVal = ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).resta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.restaResponse> CalculadoraClient.ServiceReference1.Calculadora_service.restaAsync(CalculadoraClient.ServiceReference1.restaRequest request) {
            return base.Channel.restaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.restaResponse> restaAsync(double c, double d) {
            CalculadoraClient.ServiceReference1.restaRequest inValue = new CalculadoraClient.ServiceReference1.restaRequest();
            inValue.c = c;
            inValue.d = d;
            return ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).restaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraClient.ServiceReference1.multiplicacionResponse CalculadoraClient.ServiceReference1.Calculadora_service.multiplicacion(CalculadoraClient.ServiceReference1.multiplicacionRequest request) {
            return base.Channel.multiplicacion(request);
        }
        
        public double multiplicacion(double e, double f) {
            CalculadoraClient.ServiceReference1.multiplicacionRequest inValue = new CalculadoraClient.ServiceReference1.multiplicacionRequest();
            inValue.e = e;
            inValue.f = f;
            CalculadoraClient.ServiceReference1.multiplicacionResponse retVal = ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).multiplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.multiplicacionResponse> CalculadoraClient.ServiceReference1.Calculadora_service.multiplicacionAsync(CalculadoraClient.ServiceReference1.multiplicacionRequest request) {
            return base.Channel.multiplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.multiplicacionResponse> multiplicacionAsync(double e, double f) {
            CalculadoraClient.ServiceReference1.multiplicacionRequest inValue = new CalculadoraClient.ServiceReference1.multiplicacionRequest();
            inValue.e = e;
            inValue.f = f;
            return ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).multiplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraClient.ServiceReference1.divisionResponse CalculadoraClient.ServiceReference1.Calculadora_service.division(CalculadoraClient.ServiceReference1.divisionRequest request) {
            return base.Channel.division(request);
        }
        
        public double division(double g, double h) {
            CalculadoraClient.ServiceReference1.divisionRequest inValue = new CalculadoraClient.ServiceReference1.divisionRequest();
            inValue.g = g;
            inValue.h = h;
            CalculadoraClient.ServiceReference1.divisionResponse retVal = ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).division(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.divisionResponse> CalculadoraClient.ServiceReference1.Calculadora_service.divisionAsync(CalculadoraClient.ServiceReference1.divisionRequest request) {
            return base.Channel.divisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.divisionResponse> divisionAsync(double g, double h) {
            CalculadoraClient.ServiceReference1.divisionRequest inValue = new CalculadoraClient.ServiceReference1.divisionRequest();
            inValue.g = g;
            inValue.h = h;
            return ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).divisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraClient.ServiceReference1.raizResponse CalculadoraClient.ServiceReference1.Calculadora_service.raiz(CalculadoraClient.ServiceReference1.raizRequest request) {
            return base.Channel.raiz(request);
        }
        
        public double raiz(double k) {
            CalculadoraClient.ServiceReference1.raizRequest inValue = new CalculadoraClient.ServiceReference1.raizRequest();
            inValue.k = k;
            CalculadoraClient.ServiceReference1.raizResponse retVal = ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).raiz(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.raizResponse> CalculadoraClient.ServiceReference1.Calculadora_service.raizAsync(CalculadoraClient.ServiceReference1.raizRequest request) {
            return base.Channel.raizAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraClient.ServiceReference1.raizResponse> raizAsync(double k) {
            CalculadoraClient.ServiceReference1.raizRequest inValue = new CalculadoraClient.ServiceReference1.raizRequest();
            inValue.k = k;
            return ((CalculadoraClient.ServiceReference1.Calculadora_service)(this)).raizAsync(inValue);
        }
    }
}
